- name: nginx
  debug:
    msg: "Jeste nginxe"

- block:
  - name: install
    yum:
      name: nginx
  - name: copy vhost
    template:
      src: vhost.conf
      dest: "/etc/nginx/conf.d/{{app.key}}.conf"

  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: True
  become: True

- include_tasks: consul_discovery.yml
